### ISSUE TITLE
Copy labels and only get 30 results

### ISSUE THREAD

**Issue by preillyme** [jvandemo/copy-github-labels#3]
I'm trying to copy labels from https://github.com/GoogleCloudPlatform/kubernetes to https://github.com/kubernetes-ui/kubernetes-ui-docker and only seem to get 30 of the 130 of them.

**Comment by jvandemo** [comment]
@preillyme &mdash; You are right, I just check the [GitHub API documentation](https://developer.github.com/guides/traversing-with-pagination/) and apparently they only send 30 labels per request.

There is a parameter to change the number of labels but it only allows values up to 100, so that won't help you out.

I will dig in the code to see if we can perform multiple calls behind the scenes so you don't have to deal with pagination at all.

Will keep you posted on the progress.

Thanks for your feedback!

**Comment by jvandemo** [comment]
@preillyme &mdash; I just updated the code and released v1.3.1 to support more than 30 labels.

Can you please update your dependency and try again to see if it works as expected?

No code changes are required, just update to the latest version of  `copy-github-labels`.

Thanks in advance!

**Comment by preillyme** [comment]
@jvandemo — I've got 103 now with the new updated code in ```copy-github-labels@1.3.1 node_modules/copy-github-labels```

**Comment by jvandemo** [comment]
@preillyme &mdash; I'm also getting 103 labels when I try to copy from `GoogleCloudPlatform/kubernetes`.

Does that mean you have all labels now or are you still missing some?

Thanks Patrick!

**Comment by jvandemo** [comment]
@preillyme &mdash; When I query the API directly:

https://api.github.com/repos/GoogleCloudPlatform/kubernetes/labels?per_page=100&page=1
https://api.github.com/repos/GoogleCloudPlatform/kubernetes/labels?per_page=100&page=2

I'm also getting 103 labels so I guess that concludes you are getting all labels correctly now?

Would be great if you could confirm so I can close this issue knowing that it works as expected.

Thanks again!

**Comment by preillyme** [comment]
@jvandemo seems fixed now. I appreciate it and keep up the good work.

**Comment by jvandemo** [comment]
@preillyme &mdash; Thanks for the confirmation and thanks for reporting the issue. Much appreciated!
